## test command 
## python run.py --config configs/test_batch.yml --gpu 0 --num_workers 4

## batch test met vase
run_batch_test: true
batch_size: 1 # need to be 1, component by component(extracted from full object)
checkpoint_dir: officialResults/met_vase_pretrained
checkpoint_name: checkpoint500.pth
test_result_dir_root: results/TestResults_20220825_test

load_obj: true # if false => run original method

## dataloader
image_size: 256
test_batch_data_dir_root: data/TestData_20220825_test
images_obj_dnames: ['images','objs']


## model
model_name: derender_vase
sor_circum: 96 # fit input obj data
tex_im_h: 256
tex_im_w: 768
env_map_h: 16
env_map_w: 48

## renderer
fov: 10  # in degrees
ori_z: 12.5
tx_size: 16  # 4, 8, 16
